### ISSUE TITLE
Issues in IE10/IE11

### ISSUE THREAD

**Issue by martinmacke** [karlhorky/gray#36]
I am having issues when testing the plugin in IE10 and IE11, I am getting an "Unable to get property of '0' of undefined or null reference" error in query.gray.min.js, Line: 3, Column: 2738 according to the console (see attached). This gets solved by putting <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" > into the head of the page.

![screen shot 2015-03-13 at 12 43 03](https://cloud.githubusercontent.com/assets/5556747/6638157/2a984b00-c983-11e4-8105-aab337e338fb.png)

**Comment by karlhorky** [comment]
Please provide a demo where this fails on JSFiddle or some other service.

**Comment by martinmacke** [comment]
Recreated the page here: http://jsfiddle.net/3rngsaw1/9/
Works on IE9 and below, fails on IE10 and IE11.
Putting meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" in the head solves the issue for IE10 and IE11.

**Comment by karlhorky** [comment]
This is caused by the non-numeric `background-position` and `background-size` - non-numeric values are not currently supported. You can either use numeric values for these or use images.

See the note at the end of `3.` here: https://github.com/karlhorky/gray#how-to-use

I've opened #37 and #38 to track progress on these issues. Or if you'd like to give it a shot, pull requests are welcome!

**Comment by martinmacke** [comment]
Thanks!
