### ISSUE TITLE
Shows color image ONLY on IE 10, 11

### ISSUE THREAD

**Issue by musa-pro** [karlhorky/gray#71]
I wonder why it doesn't work in IE10, 11 and throws following error

```
unable to get property 'join' of undefined or null reference
jquery.gray.min.js 3,1464

```
Btw, I'm using jquery 1.12.4
You can test it here http://bit.ly/2qJWPPl

**Comment by karlhorky** [comment]
Hi @appskitchen, this is most likely because you have a version of Modernizr on the page already but the required feature detects are not included in your Modernizr build.

In #72 I'm going to make the Developer Experience (DX) a bit better. I've [documented what to do with an existing Modernizr build](https://github.com/karlhorky/gray/pull/72/commits/ba88ba1d52e6c25b0f268bf788f1d58110f90376) and next in that pull request I will also make `gray` throw an error when the required feature detects are not included.

Edit: Error handling done in af514577ee859f417980430db53e2e5dc4ad49db

**Comment by karlhorky** [comment]
These two improvements have been deployed with `v1.6.0`:

- document how to use library with existing Modernizr
- throw error with Modernizr build that doesn't include necessary feature detects
