### ISSUE TITLE
grayscale-off on IE 11 dosn't work

### ISSUE THREAD

**Issue by Fanni-Portier** [karlhorky/gray#74]
Hi!

I can't get the grayscale-off class to work on IE.
May you can help me?

It doesn't even work on the second image with the class directly written in the html.
https://codepen.io/elkeschiffer/pen/RVLxaX

I'm sure I do something wrong - but what!?

**Comment by karlhorky** [comment]
There are a couple of things wrong here.

First of all, the event is being attached to an element that you're selecting with the `img.grayscale` selector. This element will not exist once the polyfill for IE 10, 11 and Edge 12 has run - the DOM elements will look like this:

```html
<div ...>
  <svg ...>
    <image ...></image>
  </svg>
</div>
```

So no `img` element anymore.

Secondly, the polyfill will take time to be applied elements. That means that you can only attach event handlers to the new DOM elements once they actually exist.

---

Do you only need a hover event? Because you could also do this with CSS and this will just work. The second demo on the [demo page](https://work.karlhorky.com/gray/) shows how this can work.

**Comment by Fanni-Portier** [comment]
wow - how embarrassing easy :)
thank you very much!

**Comment by karlhorky** [comment]
No problem, glad to help :)
